--CREATE TABLE "models" ( "model_id" INTEGER, "model" TEXT, "year" INTEGER, "manufacturer_id" INTEGER, "fuel_id" INTEGER, "best_mpge" INTEGER, PRIMARY KEY("model_id") );

--CREATE TABLE fuels ( fuel_id INTEGER PRIMARY KEY, fuel TEXT );

INSERT INTO manufacturers (manufacturer_id, manufacturer) VALUES
(0, 'mercedes-benz'),
(1, 'chevrolet'),
(2, 'gmc'),
(3, 'ferrari'),
(4, 'toyota'),
(5, 'bmw'),
(6, 'smart'),
(7, 'jeep'),
(8, 'ford'),
(9, 'audi'),
(10, 'jaguar'),
(11, 'kia'),
(12, 'chrysler'),
(13, 'general motors ev'),
(14, 'hyundai'),
(15, 'dodge'),
(16, 'volvo'),
(17, 'porsche'),
(18, 'lexus'),
(19, 'honda'),
(20, 'volkswagen'),
(21, 'lincoln'),
(22, 'tesla'),
(23, 'bentley motors'),
(24, 'lucid usa, inc.'),
(25, 'nissan'),
(26, 'mercury'),
(27, 'karma'),
(28, 'land rover'),
(29, 'subaru'),
(30, 'infiniti'),
(31, 'buick'),
(32, 'ram'),
(33, 'acura'),
(34, 'kandi'),
(35, 'mitsubishi'),
(36, 'cadillac'),
(37, 'mini'),
(38, 'quantum-procon'),
(39, 'mclaren'),
(40, 'solectria'),
(41, 'polestar automotive usa'),
(42, 'fiat'),
(43, 'plymouth'),
(44, 'mazda'),
(45, 'byd motors'),
(46, 'rivian'),
(47, 'scion'),
(48, 'coda automotive'),
(49, 'saturn'),
(50, 'vehicle production group'),
(51, 'hummer'),
(52, 'saab'),
(53, 'fisker automotive');